/**
 * Command Line Interface for sqlite2pg
 */

import { Command } from 'commander';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import pc from 'picocolors';
import { convert, introspect } from './index.js';
import { ConversionOptions, TargetDialect } from './types.js';
import { executeLiveMigration } from './migrate.js';
import { startApiServer } from './server.js';

export async function runCli() {
  const program = new Command();

  program
    .name('sqlite2pg')
    .description('Modern Zero-Config SQLite to PostgreSQL & Supabase Exporter & Migrator')
    .version('1.0.0');

  // Subcommand: serve API server
  program
    .command('serve')
    .description('Start the HTTP REST API server with rate limiting')
    .option('-p, --port <port>', 'Server port', '3000')
    .option('-H, --host <host>', 'Server host', '0.0.0.0')
    .option('-r, --rate-limit <max>', 'Max requests per minute per client', '60')
    .option('-k, --api-key <key>', 'Optional API key required in Authorization / X-API-Key header')
    .action((opts) => {
      const port = parseInt(opts.port, 10) || 3000;
      const rateLimit = parseInt(opts.rateLimit, 10) || 60;
      console.log(pc.cyan(`\n⚡ Starting sqlite2pg HTTP API Server on port ${pc.bold(port)}...`));
      console.log(pc.dim(`Rate Limiter: ${rateLimit} requests / minute per client IP / API Key`));
      if (opts.apiKey) {
        console.log(pc.yellow(`Auth: API key protection enabled`));
      }
      startApiServer({
        port,
        host: opts.host,
        rateLimit,
        apiKey: opts.apiKey,
        verbose: true,
      });
      console.log(pc.green(`✔ Server listening on http://${opts.host}:${port}\n`));
      console.log(pc.dim(`Endpoints:`));
      console.log(`  GET  /health          - Health check and rate limit status`);
      console.log(`  POST /api/convert     - Convert SQLite database to PostgreSQL / Supabase SQL`);
      console.log(`  POST /api/introspect  - Introspect SQLite schema structure`);
      console.log(`  POST /api/migrate     - Live migration to database\n`);
    });

  // Default migration command
  program
    .argument('[sqlite-db]', 'Path to SQLite database file (.db, .sqlite, .sqlite3)')
    .option('-o, --output <file>', 'Output SQL file (writes to stdout if omitted)')
    .option('-t, --target <dialect>', 'Target dialect: "postgres" or "supabase"', 'postgres')
    .option('-s, --schema <name>', 'PostgreSQL schema name', 'public')
    .option('-c, --conn <url>', 'Direct PostgreSQL / Supabase connection URL for live migration')
    .option('-b, --batch-size <number>', 'Batch size for INSERT statements', '1000')
    .option('--schema-only', 'Export schema only (no data)')
    .option('--data-only', 'Export data only (no DDL)')
    .option('--drop-tables', 'Include DROP TABLE IF EXISTS before table creation')
    .option('--identity', 'Use SQL standard GENERATED BY DEFAULT AS IDENTITY instead of BIGSERIAL')
    .option('--no-defer-fks', 'Do not defer foreign key constraints to end of script')
    .option('--include <tables>', 'Comma-separated list of tables to include')
    .option('--exclude <tables>', 'Comma-separated list of tables to exclude')
    .option('--dry-run', 'Inspect database and display schema summary without exporting')
    .option('--json', 'Output schema or stats in JSON format')
    .option('--verbose', 'Enable verbose logging')
    .action(async (sqlitePath: string, opts) => {
      try {
        const fullPath = resolve(process.cwd(), sqlitePath);
        if (!existsSync(fullPath)) {
          console.error(pc.red(`\n✖ Error: SQLite database file not found at: ${fullPath}\n`));
          process.exit(1);
        }

        const target = (opts.target?.toLowerCase() === 'supabase' ? 'supabase' : 'postgres') as TargetDialect;
        const includeTables = opts.include ? opts.include.split(',').map((t: string) => t.trim()) : undefined;
        const excludeTables = opts.exclude ? opts.exclude.split(',').map((t: string) => t.trim()) : undefined;

        const options: ConversionOptions = {
          target,
          schema: opts.schema,
          batchSize: parseInt(opts.batchSize, 10) || 1000,
          schemaOnly: !!opts.schemaOnly,
          dataOnly: !!opts.dataOnly,
          dropTables: !!opts.dropTables,
          identity: !!opts.identity,
          deferForeignKeys: opts.deferFks !== false,
          includeTables,
          excludeTables,
          verbose: !!opts.verbose,
        };

        // Dry Run mode
        if (opts.dryRun) {
          const intro = introspect(fullPath, options);
          if (opts.json) {
            console.log(JSON.stringify(intro, null, 2));
            return;
          }

          console.log(pc.cyan(`\n⚡ sqlite2pg Schema Inspection for: ${pc.bold(sqlitePath)}`));
          console.log(pc.dim(`------------------------------------------------------------`));
          console.log(`Found ${pc.green(pc.bold(intro.tables.length))} tables, ${pc.blue(intro.views.length)} views, ~${pc.yellow(intro.totalRows)} total rows.\n`);

          for (const t of intro.tables) {
            console.log(
              `  ${pc.bold(t.name)} (${pc.yellow(t.rowCount ?? 0)} rows, ${t.columns.length} cols, ${t.foreignKeys.length} FKs, ${t.indexes.length} idxs)`
            );
            if (opts.verbose) {
              for (const c of t.columns) {
                const pkBadge = c.isPk ? pc.magenta(' [PK]') : '';
                const nnBadge = c.notNull ? pc.dim(' NOT NULL') : '';
                console.log(`    - ${c.name}: ${pc.cyan(c.sqliteType || 'ANY')}${pkBadge}${nnBadge}`);
              }
            }
          }
          console.log(pc.dim(`\nDry run completed.\n`));
          return;
        }

        // Execution
        const result = convert(fullPath, options);

        if (opts.json) {
          console.log(
            JSON.stringify(
              {
                stats: result.stats,
                output: opts.output || null,
              },
              null,
              2
            )
          );
          return;
        }

        // Direct Live Migration
        if (opts.conn) {
          console.log(pc.cyan(`\n🚀 Starting live migration to PostgreSQL...`));
          const migration = await executeLiveMigration(opts.conn, result, options);
          if (!migration.success) {
            console.error(pc.red(`\n✖ Live migration failed: ${migration.error?.message}\n`));
            process.exit(1);
          }
          console.log(pc.green(`✔ Live migration successfully applied in ${result.stats.durationMs}ms!\n`));
          printStats(result.stats);
          return;
        }

        // File Output or Stdout
        if (opts.output) {
          const outPath = resolve(process.cwd(), opts.output);
          writeFileSync(outPath, result.sql, 'utf-8');
          console.log(pc.green(`\n✔ Migration SQL written to: ${pc.bold(opts.output)}`));
          printStats(result.stats);
        } else {
          // stdout
          process.stdout.write(result.sql);
        }
      } catch (err: any) {
        console.error(pc.red(`\n✖ Error: ${err?.message || err}\n`));
        if (opts.verbose && err?.stack) {
          console.error(pc.dim(err.stack));
        }
        process.exit(1);
      }
    });

  await program.parseAsync(process.argv);
}

function printStats(stats: any) {
  console.log(pc.dim(`------------------------------------------------------------`));
  console.log(
    `Tables: ${pc.bold(pc.green(stats.tableCount))} | Rows: ${pc.bold(pc.yellow(stats.rowCount))} | FKs: ${stats.foreignKeyCount} | Indexes: ${stats.indexCount} | Duration: ${stats.durationMs}ms`
  );
  console.log(pc.dim(`------------------------------------------------------------\n`));
}
