/**
 * PostgreSQL and Supabase SQL Migration Generator
 */

import { DatabaseSync } from 'node:sqlite';
import {
  ConversionOptions,
  ConversionResult,
  IntrospectionResult,
  TableInfo,
  ColumnInfo,
  MigrationStats,
} from './types.js';
import { mapSqliteTypeToPostgres, quoteIdent, sanitizeDefaultValue } from './type-mapper.js';
import { transformValue } from './transform.js';

export function generateMigrationSql(
  db: DatabaseSync,
  introspection: IntrospectionResult,
  options: ConversionOptions = {}
): ConversionResult {
  const startTime = Date.now();
  const target = options.target || 'postgres';
  const schema = options.schema || 'public';
  const batchSize = Math.max(1, options.batchSize || 1000);
  const isSupabase = target === 'supabase';
  const enableRls = options.enableRls ?? isSupabase;
  const deferFks = options.deferForeignKeys ?? true;

  const sqlLines: string[] = [];

  // 1. Header & Configuration
  sqlLines.push(`-- ============================================================`);
  sqlLines.push(`-- Generated by sqlite2pg (SQLite to PostgreSQL / Supabase)`);
  sqlLines.push(`-- Target: ${target.toUpperCase()}`);
  sqlLines.push(`-- Schema: "${schema}"`);
  sqlLines.push(`-- Generated at: ${new Date().toISOString()}`);
  sqlLines.push(`-- Tables: ${introspection.tables.length} | Rows: ${introspection.totalRows}`);
  sqlLines.push(`-- ============================================================\n`);

  sqlLines.push(`BEGIN;\n`);
  sqlLines.push(`SET client_encoding = 'UTF8';`);
  sqlLines.push(`SET standard_conforming_strings = on;`);
  sqlLines.push(`SET check_function_bodies = false;`);
  sqlLines.push(`SET client_min_messages = warning;`);
  if (schema !== 'public') {
    sqlLines.push(`CREATE SCHEMA IF NOT EXISTS ${quoteIdent(schema)};`);
  }
  sqlLines.push(`SET search_path = ${quoteIdent(schema)}, public;\n`);

  if (isSupabase) {
    sqlLines.push(`-- Supabase Extensions`);
    sqlLines.push(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);
    sqlLines.push(`CREATE EXTENSION IF NOT EXISTS "pgcrypto";\n`);
  }

  let foreignKeyCount = 0;
  let indexCount = 0;
  let sequenceCount = 0;
  let totalExportedRows = 0;

  // 2. Drop Tables if requested
  if (options.dropTables && !options.dataOnly) {
    sqlLines.push(`-- ------------------------------------------------------------`);
    sqlLines.push(`-- Drop Existing Tables`);
    sqlLines.push(`-- ------------------------------------------------------------`);
    for (let i = introspection.tables.length - 1; i >= 0; i--) {
      const table = introspection.tables[i];
      sqlLines.push(`DROP TABLE IF EXISTS ${quoteIdent(table.name, schema)} CASCADE;`);
    }
    sqlLines.push('');
  }

  // 3. Table DDL Creation (if not data-only)
  if (!options.dataOnly) {
    sqlLines.push(`-- ------------------------------------------------------------`);
    sqlLines.push(`-- Table Definitions`);
    sqlLines.push(`-- ------------------------------------------------------------`);

    for (const table of introspection.tables) {
      sqlLines.push(`-- Table: ${table.name}`);
      const colDefs: string[] = [];
      const hasCompositePk = table.primaryKeys.length > 1;
      const isOnlyPk = table.primaryKeys.length === 1;

      for (const col of table.columns) {
        const isSinglePkCol = isOnlyPk && col.isPk;
        const pgType = mapSqliteTypeToPostgres(col, {
          identity: options.identity,
          isOnlyPk: isSinglePkCol,
        });

        let colDef = `  ${quoteIdent(col.name)} ${pgType}`;

        // Single Primary Key definition
        if (isSinglePkCol) {
          colDef += ` PRIMARY KEY`;
        }

        // NOT NULL
        if (col.notNull && !isSinglePkCol) {
          colDef += ` NOT NULL`;
        }

        // DEFAULT VALUE
        if (col.defaultValue !== null && col.defaultValue !== undefined && !isSinglePkCol) {
          const sanitizedDef = sanitizeDefaultValue(col.defaultValue, pgType);
          if (sanitizedDef !== null) {
            colDef += ` DEFAULT ${sanitizedDef}`;
          }
        }

        colDefs.push(colDef);

        if (col.isAutoincrement || pgType.includes('SERIAL') || pgType.includes('IDENTITY')) {
          sequenceCount++;
        }
      }

      // Composite Primary Key
      if (hasCompositePk) {
        const quotedPks = table.primaryKeys.map((pk) => quoteIdent(pk)).join(', ');
        colDefs.push(`  CONSTRAINT "${table.name}_pkey" PRIMARY KEY (${quotedPks})`);
      }

      // Inline Foreign Keys (only if NOT deferred)
      if (!deferFks && table.foreignKeys.length > 0) {
        for (let i = 0; i < table.foreignKeys.length; i++) {
          const fk = table.foreignKeys[i];
          let fkClause = `  CONSTRAINT "${table.name}_fk_${i + 1}" FOREIGN KEY (${quoteIdent(fk.from)}) REFERENCES ${quoteIdent(fk.table, schema)} (${quoteIdent(fk.to)})`;
          if (fk.onDelete && fk.onDelete !== 'NONE' && fk.onDelete !== 'NO ACTION') {
            fkClause += ` ON DELETE ${fk.onDelete.toUpperCase()}`;
          }
          if (fk.onUpdate && fk.onUpdate !== 'NONE' && fk.onUpdate !== 'NO ACTION') {
            fkClause += ` ON UPDATE ${fk.onUpdate.toUpperCase()}`;
          }
          colDefs.push(fkClause);
          foreignKeyCount++;
        }
      }

      sqlLines.push(`CREATE TABLE IF NOT EXISTS ${quoteIdent(table.name, schema)} (`);
      sqlLines.push(colDefs.join(',\n'));
      sqlLines.push(`);\n`);

      // Supabase / RLS
      if (enableRls) {
        sqlLines.push(`ALTER TABLE ${quoteIdent(table.name, schema)} ENABLE ROW LEVEL SECURITY;\n`);
      }
    }
  }

  // 4. Data Insertion (if not schema-only)
  if (!options.schemaOnly && introspection.tables.length > 0) {
    sqlLines.push(`-- ------------------------------------------------------------`);
    sqlLines.push(`-- Data Migration`);
    sqlLines.push(`-- ------------------------------------------------------------\n`);

    for (const table of introspection.tables) {
      if (table.columns.length === 0) continue;

      const countStmt = db.prepare(`SELECT COUNT(*) as count FROM "${table.name.replace(/"/g, '""')}";`);
      const countResult = countStmt.get() as { count: number | bigint };
      const tableRows = Number(countResult.count);

      if (tableRows === 0) {
        sqlLines.push(`-- Table "${table.name}": 0 rows\n`);
        continue;
      }

      sqlLines.push(`-- Data for Table: "${table.name}" (${tableRows} rows)`);

      // Prepare column list & types
      const colNames = table.columns.map((c) => quoteIdent(c.name)).join(', ');
      const colPgTypes = table.columns.map((c) =>
        mapSqliteTypeToPostgres(c, {
          identity: options.identity,
          isOnlyPk: table.primaryKeys.length === 1 && c.isPk,
        })
      );

      // Select and stream rows in chunks
      const selectStmt = db.prepare(`SELECT * FROM "${table.name.replace(/"/g, '""')}";`);
      const allRows = selectStmt.all() as Array<Record<string, unknown>>;

      for (let i = 0; i < allRows.length; i += batchSize) {
        const batch = allRows.slice(i, i + batchSize);
        const valueTuples: string[] = [];

        for (const row of batch) {
          const rowValues: string[] = [];
          for (let c = 0; c < table.columns.length; c++) {
            const col = table.columns[c];
            const val = row[col.name];
            rowValues.push(transformValue(val, colPgTypes[c]));
          }
          valueTuples.push(`  (${rowValues.join(', ')})`);
        }

        sqlLines.push(
          `INSERT INTO ${quoteIdent(table.name, schema)} (${colNames})\nVALUES\n${valueTuples.join(',\n')};\n`
        );
        totalExportedRows += batch.length;
      }
    }
  }

  // 5. Indexes (created after data load for maximum speed)
  if (!options.dataOnly) {
    let hasIndexes = false;
    for (const table of introspection.tables) {
      if (table.indexes.length > 0) {
        hasIndexes = true;
        break;
      }
    }

    if (hasIndexes) {
      sqlLines.push(`-- ------------------------------------------------------------`);
      sqlLines.push(`-- Indexes`);
      sqlLines.push(`-- ------------------------------------------------------------`);

      for (const table of introspection.tables) {
        for (const idx of table.indexes) {
          const uniqueStr = idx.unique ? 'UNIQUE ' : '';
          const quotedCols = idx.columns
            .map((c) => `${quoteIdent(c.name)}${c.desc ? ' DESC' : ''}`)
            .join(', ');

          if (quotedCols.length > 0) {
            const safeIdxName = `idx_${table.name}_${idx.name}`.replace(/[^a-zA-Z0-9_]/g, '_');
            sqlLines.push(
              `CREATE ${uniqueStr}INDEX IF NOT EXISTS "${safeIdxName}" ON ${quoteIdent(table.name, schema)} (${quotedCols});`
            );
            indexCount++;
          }
        }
      }
      sqlLines.push('');
    }
  }

  // 6. Deferred Foreign Key Constraints (guarantees zero foreign-key ordering issues)
  if (!options.dataOnly && deferFks) {
    let hasFks = false;
    for (const table of introspection.tables) {
      if (table.foreignKeys.length > 0) {
        hasFks = true;
        break;
      }
    }

    if (hasFks) {
      sqlLines.push(`-- ------------------------------------------------------------`);
      sqlLines.push(`-- Foreign Key Constraints (Deferred for Safe Data Loading)`);
      sqlLines.push(`-- ------------------------------------------------------------`);

      for (const table of introspection.tables) {
        for (let i = 0; i < table.foreignKeys.length; i++) {
          const fk = table.foreignKeys[i];
          const fkName = `fk_${table.name}_${fk.from}_${i + 1}`.replace(/[^a-zA-Z0-9_]/g, '_');
          let fkSql = `ALTER TABLE ${quoteIdent(table.name, schema)} ADD CONSTRAINT "${fkName}" FOREIGN KEY (${quoteIdent(fk.from)}) REFERENCES ${quoteIdent(fk.table, schema)} (${quoteIdent(fk.to)})`;

          if (fk.onDelete && fk.onDelete !== 'NONE' && fk.onDelete !== 'NO ACTION') {
            fkSql += ` ON DELETE ${fk.onDelete.toUpperCase()}`;
          }
          if (fk.onUpdate && fk.onUpdate !== 'NONE' && fk.onUpdate !== 'NO ACTION') {
            fkSql += ` ON UPDATE ${fk.onUpdate.toUpperCase()}`;
          }
          fkSql += `;`;

          sqlLines.push(fkSql);
          foreignKeyCount++;
        }
      }
      sqlLines.push('');
    }
  }

  // 7. Sequence Synchronization (setval)
  // Essential: Fixes the number one silent bug where Postgres fails on next INSERT
  if (!options.schemaOnly && introspection.tables.length > 0) {
    sqlLines.push(`-- ------------------------------------------------------------`);
    sqlLines.push(`-- Sequence Synchronization (Prevents Duplicate Key Errors)`);
    sqlLines.push(`-- ------------------------------------------------------------`);

    for (const table of introspection.tables) {
      for (const col of table.columns) {
        if (col.isAutoincrement || (col.isPk && table.primaryKeys.length === 1)) {
          // Check if sequence exists
          sqlLines.push(
            `DO $$ BEGIN ` +
            `IF pg_get_serial_sequence('${schema}.${table.name}', '${col.name}') IS NOT NULL THEN ` +
            `PERFORM setval(pg_get_serial_sequence('${schema}.${table.name}', '${col.name}'), coalesce(max(${quoteIdent(col.name)}), 1), max(${quoteIdent(col.name)}) IS NOT NULL) FROM ${quoteIdent(table.name, schema)}; ` +
            `END IF; END $$;`
          );
        }
      }
    }
    sqlLines.push('');
  }

  // 8. Views (if any)
  if (!options.dataOnly && introspection.views.length > 0) {
    sqlLines.push(`-- ------------------------------------------------------------`);
    sqlLines.push(`-- Views`);
    sqlLines.push(`-- ------------------------------------------------------------`);
    for (const view of introspection.views) {
      sqlLines.push(`-- Original SQLite View: ${view.name}`);
      // SQLite view SQL usually begins with CREATE VIEW ...
      sqlLines.push(`${view.sql};\n`);
    }
  }

  // 9. Commit Transaction
  sqlLines.push(`COMMIT;\n`);

  const durationMs = Date.now() - startTime;
  const stats: MigrationStats = {
    tableCount: introspection.tables.length,
    viewCount: introspection.views.length,
    rowCount: totalExportedRows,
    foreignKeyCount,
    indexCount,
    sequenceCount,
    durationMs,
  };

  return {
    sql: sqlLines.join('\n'),
    stats,
  };
}
