/**
 * SQLite to PostgreSQL Type Mapping & Expression Sanitization
 */

import { ColumnInfo } from './types.js';

/**
 * Quotes a SQL identifier (table, column, schema name) using PostgreSQL standard double quotes.
 */
export function quoteIdent(identifier: string, schema?: string): string {
  const cleanIdent = identifier.replace(/"/g, '""');
  if (schema) {
    const cleanSchema = schema.replace(/"/g, '""');
    return `"${cleanSchema}"."${cleanIdent}"`;
  }
  return `"${cleanIdent}"`;
}

/**
 * Maps SQLite column type declarations and dynamic samples to strict PostgreSQL types.
 */
export function mapSqliteTypeToPostgres(
  column: ColumnInfo,
  options: { identity?: boolean; isOnlyPk?: boolean } = {}
): string {
  const rawType = (column.sqliteType || '').trim().toUpperCase();

  // If this column is a single integer primary key (SQLite's rowid alias)
  if (column.isPk && options.isOnlyPk && (rawType === 'INTEGER' || rawType === 'INT' || column.isAutoincrement)) {
    if (options.identity) {
      return 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
    }
    return 'BIGSERIAL';
  }

  // Exact type mappings or regex patterns
  if (!rawType || rawType === '' || rawType === 'NONE') {
    // If no type specified in SQLite, fallback based on inferred type or TEXT
    return column.inferredPostgresType || 'TEXT';
  }

  // Boolean aliases
  if (/^(BOOLEAN|BOOL|TINYINT\s*\(\s*1\s*\)|BIT)$/i.test(rawType)) {
    return 'BOOLEAN';
  }

  // Integers
  if (/^TINYINT(\s*\(\s*\d+\s*\))?$/i.test(rawType) || /^SMALLINT$/i.test(rawType) || /^INT2$/i.test(rawType)) {
    return 'SMALLINT';
  }
  if (/^BIGINT$/i.test(rawType) || /^INT8$/i.test(rawType) || /^UNSIGNED\s+BIG\s+INT$/i.test(rawType)) {
    return 'BIGINT';
  }
  if (/^(INT|INTEGER|MEDIUMINT|INT4|SERIAL|BIGSERIAL)$/i.test(rawType)) {
    return 'INTEGER';
  }

  // Floating point & arbitrary precision
  if (/^(REAL|FLOAT|DOUBLE|DOUBLE\s+PRECISION)$/i.test(rawType)) {
    return 'DOUBLE PRECISION';
  }
  if (/^(NUMERIC|DECIMAL)(\s*\(\s*\d+(\s*,\s*\d+)?\s*\))?$/i.test(rawType)) {
    return rawType; // keeps NUMERIC(10,2) intact
  }

  // JSON / JSONB
  if (/^(JSON|JSONB)$/i.test(rawType)) {
    return 'JSONB';
  }

  // UUID
  if (/^(UUID|GUID)$/i.test(rawType)) {
    return 'UUID';
  }

  // Date & Time
  if (/^(DATETIME|TIMESTAMP|TIMESTAMPTZ)$/i.test(rawType)) {
    return 'TIMESTAMPTZ';
  }
  if (/^DATE$/i.test(rawType)) {
    return 'DATE';
  }
  if (/^TIME$/i.test(rawType)) {
    return 'TIME';
  }

  // BLOB / Binary
  if (/^(BLOB|BYTEA|BINARY|VARBINARY|IMAGE)$/i.test(rawType)) {
    return 'BYTEA';
  }

  // Strings / Varchar
  const varcharMatch = rawType.match(/^VARCHAR\s*\(\s*(\d+)\s*\)$/i);
  if (varcharMatch) {
    return `VARCHAR(${varcharMatch[1]})`;
  }
  const charMatch = rawType.match(/^CHAR\s*\(\s*(\d+)\s*\)$/i);
  if (charMatch) {
    return `CHAR(${charMatch[1]})`;
  }
  if (/^(TEXT|CLOB|LONGTEXT|MEDIUMTEXT|TINYTEXT|STRING)$/i.test(rawType)) {
    return 'TEXT';
  }

  // SQLite affinity rules fallback:
  if (rawType.includes('INT')) return 'INTEGER';
  if (rawType.includes('CHAR') || rawType.includes('CLOB') || rawType.includes('TEXT')) return 'TEXT';
  if (rawType.includes('BLOB')) return 'BYTEA';
  if (rawType.includes('REAL') || rawType.includes('FLOA') || rawType.includes('DOUB')) return 'DOUBLE PRECISION';
  if (rawType.includes('NUMERIC') || rawType.includes('DECIMAL')) return 'NUMERIC';

  return 'TEXT';
}

/**
 * Sanitizes SQLite column default value expressions to valid PostgreSQL default expressions.
 */
export function sanitizeDefaultValue(
  defaultValue: string | null,
  pgType: string
): string | null {
  if (defaultValue === null || defaultValue === undefined) {
    return null;
  }

  let def = defaultValue.trim();

  // Strip wrapping outer parentheses if any, e.g. (1) -> 1 or ('abc') -> 'abc'
  while (def.startsWith('(') && def.endsWith(')')) {
    const inner = def.slice(1, -1).trim();
    // avoid stripping if it's a function or expression with nested parens
    if (inner.includes('(') && !inner.endsWith(')')) break;
    def = inner;
  }

  if (def.toUpperCase() === 'NULL') {
    return 'NULL';
  }

  // Boolean defaults
  if (pgType === 'BOOLEAN') {
    if (def === '1' || def === "'1'" || def.toLowerCase() === "'true'" || def.toLowerCase() === 'true') {
      return 'TRUE';
    }
    if (def === '0' || def === "'0'" || def.toLowerCase() === "'false'" || def.toLowerCase() === 'false') {
      return 'FALSE';
    }
  }

  // Date/Time functions
  if (/^CURRENT_TIMESTAMP$/i.test(def) || /^CURRENT_DATE$/i.test(def) || /^CURRENT_TIME$/i.test(def)) {
    return def.toUpperCase();
  }
  if (/^datetime\s*\(\s*['"]now['"]\s*\)$/i.test(def) || /^now\s*\(\s*\)$/i.test(def)) {
    return 'NOW()';
  }
  if (/^strftime\s*\(\s*['"]%s['"]\s*,\s*['"]now['"]\s*\)$/i.test(def)) {
    return 'EXTRACT(EPOCH FROM NOW())::BIGINT';
  }
  if (/^(uuid\s*\(\s*\)|lower\s*\(\s*hex\s*\(\s*randomblob\s*\(\s*16\s*\)\s*\)\s*\))$/i.test(def)) {
    return 'gen_random_uuid()';
  }

  return def;
}
